// Package queue defines the interface for queue backends.
//
// This package provides a clean abstraction over different queue implementations
// (e.g., GCP Pub/Sub). Implementations should be added as separate files under
// internal/queue/.
package queue

import (
	"context"
	"errors"
	"time"
)

// Common errors returned by queue backends.
var (
	ErrQueueUnavailable = errors.New("queue backend unavailable")
	ErrJobTooLarge      = errors.New("job payload exceeds maximum size")
	ErrInvalidJob       = errors.New("invalid job")
)

// Priority represents the priority queue for job execution.
type Priority int

const (
	PriorityUnspecified Priority = iota
	PriorityImmediate            // SLA: ≤5 seconds
	PriorityHigh                 // SLA: ≤15 seconds
	PriorityMedium               // SLA: ≤1 minute
	PriorityLow                  // SLA: ≤5 minutes
)

func (p Priority) String() string {
	switch p {
	case PriorityImmediate:
		return "immediate"
	case PriorityHigh:
		return "high"
	case PriorityMedium:
		return "medium"
	case PriorityLow:
		return "low"
	default:
		return "unspecified"
	}
}

// Job represents a background job to be enqueued.
type Job struct {
	// ID is the unique job identifier (generated by the service).
	ID string

	// ProducerID is the producer that owns this job.
	ProducerID string

	// Type is the job type name.
	Type string

	// Priority determines which queue the job is placed in.
	Priority Priority

	// Payload is the opaque data delivered to the consumer.
	Payload []byte

	// RunAt is when the job should be executed.
	// If zero, the job runs immediately.
	RunAt time.Time

	// TraceID is the distributed tracing correlation ID.
	TraceID string

	// MaxRetries is the maximum number of retry attempts.
	MaxRetries int

	// CreatedAt is when the job was created.
	CreatedAt time.Time

	// Shadow indicates this job was enqueued in shadow/migration mode.
	// When true, consumers can use this to distinguish Jack-path vs Dispatcher-path messages.
	Shadow bool
}

// EnqueueResult represents the result of enqueueing a single job.
type EnqueueResult struct {
	// JobID is the unique identifier for the enqueued job.
	JobID string

	// Error is set if the job failed to enqueue.
	Error error
}

// Backend defines the interface that queue implementations must satisfy.
type Backend interface {
	// Enqueue adds a single job to the queue.
	// Returns the job ID on success, or an error on failure.
	Enqueue(ctx context.Context, job *Job) error

	// EnqueueBulk adds multiple jobs to the queue.
	// This is a best-effort operation - some jobs may succeed while others fail.
	// Returns a result for each job in the same order as the input.
	EnqueueBulk(ctx context.Context, jobs []*Job) []EnqueueResult

	// Health checks if the queue backend is healthy and accepting jobs.
	Health(ctx context.Context) error

	// Close gracefully shuts down the queue backend.
	Close() error
}

// BackendConfig contains configuration for queue backends.
type BackendConfig struct {
	// MaxPayloadSize is the maximum allowed payload size in bytes.
	// Default: 1MB (1048576 bytes)
	MaxPayloadSize int

	// DefaultMaxRetries is the default retry count for jobs.
	// Default: 10
	DefaultMaxRetries int

	// EnqueueTimeout is the timeout for enqueue operations.
	// Default: 30 seconds
	EnqueueTimeout time.Duration
}

// DefaultConfig returns the default backend configuration.
func DefaultConfig() BackendConfig {
	return BackendConfig{
		MaxPayloadSize:    1048576, // 1MB
		DefaultMaxRetries: 10,
		EnqueueTimeout:    30 * time.Second,
	}
}

// Validate checks if a job is valid for enqueueing.
func (j *Job) Validate(maxPayloadSize int) error {
	if j.ProducerID == "" {
		return errors.New("producer_id is required")
	}
	if j.Type == "" {
		return errors.New("job_type is required")
	}
	if maxPayloadSize > 0 && len(j.Payload) > maxPayloadSize {
		return ErrJobTooLarge
	}
	return nil
}
