// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: admin.proto

package jackpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_CreateProducer_FullMethodName = "/jack.AdminService/CreateProducer"
	AdminService_GetProducer_FullMethodName    = "/jack.AdminService/GetProducer"
	AdminService_ListProducers_FullMethodName  = "/jack.AdminService/ListProducers"
	AdminService_CreateJobType_FullMethodName  = "/jack.AdminService/CreateJobType"
	AdminService_ListJobTypes_FullMethodName   = "/jack.AdminService/ListJobTypes"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService provides CRUD operations for producers and job types.
// Used by the admin console to manage configuration.
type AdminServiceClient interface {
	// CreateProducer registers a new producer.
	// The server generates the producer_id (prod_* format).
	CreateProducer(ctx context.Context, in *CreateProducerRequest, opts ...grpc.CallOption) (*CreateProducerResponse, error)
	// GetProducer retrieves a single producer by ID.
	GetProducer(ctx context.Context, in *GetProducerRequest, opts ...grpc.CallOption) (*GetProducerResponse, error)
	// ListProducers returns all registered producers.
	ListProducers(ctx context.Context, in *ListProducersRequest, opts ...grpc.CallOption) (*ListProducersResponse, error)
	// CreateJobType registers a new job type for a producer.
	CreateJobType(ctx context.Context, in *CreateJobTypeRequest, opts ...grpc.CallOption) (*CreateJobTypeResponse, error)
	// ListJobTypes returns all job types for a given producer.
	ListJobTypes(ctx context.Context, in *ListJobTypesRequest, opts ...grpc.CallOption) (*ListJobTypesResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) CreateProducer(ctx context.Context, in *CreateProducerRequest, opts ...grpc.CallOption) (*CreateProducerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProducerResponse)
	err := c.cc.Invoke(ctx, AdminService_CreateProducer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetProducer(ctx context.Context, in *GetProducerRequest, opts ...grpc.CallOption) (*GetProducerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProducerResponse)
	err := c.cc.Invoke(ctx, AdminService_GetProducer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListProducers(ctx context.Context, in *ListProducersRequest, opts ...grpc.CallOption) (*ListProducersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProducersResponse)
	err := c.cc.Invoke(ctx, AdminService_ListProducers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateJobType(ctx context.Context, in *CreateJobTypeRequest, opts ...grpc.CallOption) (*CreateJobTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateJobTypeResponse)
	err := c.cc.Invoke(ctx, AdminService_CreateJobType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListJobTypes(ctx context.Context, in *ListJobTypesRequest, opts ...grpc.CallOption) (*ListJobTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobTypesResponse)
	err := c.cc.Invoke(ctx, AdminService_ListJobTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService provides CRUD operations for producers and job types.
// Used by the admin console to manage configuration.
type AdminServiceServer interface {
	// CreateProducer registers a new producer.
	// The server generates the producer_id (prod_* format).
	CreateProducer(context.Context, *CreateProducerRequest) (*CreateProducerResponse, error)
	// GetProducer retrieves a single producer by ID.
	GetProducer(context.Context, *GetProducerRequest) (*GetProducerResponse, error)
	// ListProducers returns all registered producers.
	ListProducers(context.Context, *ListProducersRequest) (*ListProducersResponse, error)
	// CreateJobType registers a new job type for a producer.
	CreateJobType(context.Context, *CreateJobTypeRequest) (*CreateJobTypeResponse, error)
	// ListJobTypes returns all job types for a given producer.
	ListJobTypes(context.Context, *ListJobTypesRequest) (*ListJobTypesResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) CreateProducer(context.Context, *CreateProducerRequest) (*CreateProducerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProducer not implemented")
}
func (UnimplementedAdminServiceServer) GetProducer(context.Context, *GetProducerRequest) (*GetProducerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProducer not implemented")
}
func (UnimplementedAdminServiceServer) ListProducers(context.Context, *ListProducersRequest) (*ListProducersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProducers not implemented")
}
func (UnimplementedAdminServiceServer) CreateJobType(context.Context, *CreateJobTypeRequest) (*CreateJobTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateJobType not implemented")
}
func (UnimplementedAdminServiceServer) ListJobTypes(context.Context, *ListJobTypesRequest) (*ListJobTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobTypes not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_CreateProducer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProducerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateProducer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateProducer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateProducer(ctx, req.(*CreateProducerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetProducer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProducerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetProducer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetProducer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetProducer(ctx, req.(*GetProducerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListProducers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProducersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListProducers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListProducers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListProducers(ctx, req.(*ListProducersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateJobType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateJobType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateJobType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateJobType(ctx, req.(*CreateJobTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListJobTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListJobTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListJobTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListJobTypes(ctx, req.(*ListJobTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jack.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProducer",
			Handler:    _AdminService_CreateProducer_Handler,
		},
		{
			MethodName: "GetProducer",
			Handler:    _AdminService_GetProducer_Handler,
		},
		{
			MethodName: "ListProducers",
			Handler:    _AdminService_ListProducers_Handler,
		},
		{
			MethodName: "CreateJobType",
			Handler:    _AdminService_CreateJobType_Handler,
		},
		{
			MethodName: "ListJobTypes",
			Handler:    _AdminService_ListJobTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
