// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin.proto

package jackpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProducerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Display name for the producer (required).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional description.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProducerRequest) Reset() {
	*x = CreateProducerRequest{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProducerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProducerRequest) ProtoMessage() {}

func (x *CreateProducerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProducerRequest.ProtoReflect.Descriptor instead.
func (*CreateProducerRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProducerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProducerRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateProducerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created producer with server-generated ID and timestamps.
	Producer      *Producer `protobuf:"bytes,1,opt,name=producer,proto3" json:"producer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProducerResponse) Reset() {
	*x = CreateProducerResponse{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProducerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProducerResponse) ProtoMessage() {}

func (x *CreateProducerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProducerResponse.ProtoReflect.Descriptor instead.
func (*CreateProducerResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProducerResponse) GetProducer() *Producer {
	if x != nil {
		return x.Producer
	}
	return nil
}

type GetProducerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The producer ID to look up (required).
	ProducerId    string `protobuf:"bytes,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProducerRequest) Reset() {
	*x = GetProducerRequest{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProducerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProducerRequest) ProtoMessage() {}

func (x *GetProducerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProducerRequest.ProtoReflect.Descriptor instead.
func (*GetProducerRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GetProducerRequest) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

type GetProducerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Producer      *Producer              `protobuf:"bytes,1,opt,name=producer,proto3" json:"producer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProducerResponse) Reset() {
	*x = GetProducerResponse{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProducerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProducerResponse) ProtoMessage() {}

func (x *GetProducerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProducerResponse.ProtoReflect.Descriptor instead.
func (*GetProducerResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetProducerResponse) GetProducer() *Producer {
	if x != nil {
		return x.Producer
	}
	return nil
}

type ListProducersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProducersRequest) Reset() {
	*x = ListProducersRequest{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProducersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProducersRequest) ProtoMessage() {}

func (x *ListProducersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProducersRequest.ProtoReflect.Descriptor instead.
func (*ListProducersRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

type ListProducersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Producers     []*Producer            `protobuf:"bytes,1,rep,name=producers,proto3" json:"producers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProducersResponse) Reset() {
	*x = ListProducersResponse{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProducersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProducersResponse) ProtoMessage() {}

func (x *ListProducersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProducersResponse.ProtoReflect.Descriptor instead.
func (*ListProducersResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListProducersResponse) GetProducers() []*Producer {
	if x != nil {
		return x.Producers
	}
	return nil
}

type CreateJobTypeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The producer this job type belongs to (required).
	ProducerId string `protobuf:"bytes,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	// Job type name (required).
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Queue priority.
	Queue Queue `protobuf:"varint,3,opt,name=queue,proto3,enum=jack.Queue" json:"queue,omitempty"`
	// Maximum retry attempts (defaults to 3 if not set).
	MaxRetries int32 `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	// Optional description.
	Description   string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobTypeRequest) Reset() {
	*x = CreateJobTypeRequest{}
	mi := &file_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobTypeRequest) ProtoMessage() {}

func (x *CreateJobTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateJobTypeRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{6}
}

func (x *CreateJobTypeRequest) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *CreateJobTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateJobTypeRequest) GetQueue() Queue {
	if x != nil {
		return x.Queue
	}
	return Queue_QUEUE_UNSPECIFIED
}

func (x *CreateJobTypeRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *CreateJobTypeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateJobTypeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created job type.
	JobType       *JobType `protobuf:"bytes,1,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobTypeResponse) Reset() {
	*x = CreateJobTypeResponse{}
	mi := &file_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobTypeResponse) ProtoMessage() {}

func (x *CreateJobTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobTypeResponse.ProtoReflect.Descriptor instead.
func (*CreateJobTypeResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{7}
}

func (x *CreateJobTypeResponse) GetJobType() *JobType {
	if x != nil {
		return x.JobType
	}
	return nil
}

type ListJobTypesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The producer whose job types to list (required).
	ProducerId    string `protobuf:"bytes,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobTypesRequest) Reset() {
	*x = ListJobTypesRequest{}
	mi := &file_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobTypesRequest) ProtoMessage() {}

func (x *ListJobTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobTypesRequest.ProtoReflect.Descriptor instead.
func (*ListJobTypesRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ListJobTypesRequest) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

type ListJobTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobTypes      []*JobType             `protobuf:"bytes,1,rep,name=job_types,json=jobTypes,proto3" json:"job_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobTypesResponse) Reset() {
	*x = ListJobTypesResponse{}
	mi := &file_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobTypesResponse) ProtoMessage() {}

func (x *ListJobTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobTypesResponse.ProtoReflect.Descriptor instead.
func (*ListJobTypesResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ListJobTypesResponse) GetJobTypes() []*JobType {
	if x != nil {
		return x.JobTypes
	}
	return nil
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\x04jack\x1a\rstorage.proto\"M\n" +
	"\x15CreateProducerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"D\n" +
	"\x16CreateProducerResponse\x12*\n" +
	"\bproducer\x18\x01 \x01(\v2\x0e.jack.ProducerR\bproducer\"5\n" +
	"\x12GetProducerRequest\x12\x1f\n" +
	"\vproducer_id\x18\x01 \x01(\tR\n" +
	"producerId\"A\n" +
	"\x13GetProducerResponse\x12*\n" +
	"\bproducer\x18\x01 \x01(\v2\x0e.jack.ProducerR\bproducer\"\x16\n" +
	"\x14ListProducersRequest\"E\n" +
	"\x15ListProducersResponse\x12,\n" +
	"\tproducers\x18\x01 \x03(\v2\x0e.jack.ProducerR\tproducers\"\xb1\x01\n" +
	"\x14CreateJobTypeRequest\x12\x1f\n" +
	"\vproducer_id\x18\x01 \x01(\tR\n" +
	"producerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\x05queue\x18\x03 \x01(\x0e2\v.jack.QueueR\x05queue\x12\x1f\n" +
	"\vmax_retries\x18\x04 \x01(\x05R\n" +
	"maxRetries\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"A\n" +
	"\x15CreateJobTypeResponse\x12(\n" +
	"\bjob_type\x18\x01 \x01(\v2\r.jack.JobTypeR\ajobType\"6\n" +
	"\x13ListJobTypesRequest\x12\x1f\n" +
	"\vproducer_id\x18\x01 \x01(\tR\n" +
	"producerId\"B\n" +
	"\x14ListJobTypesResponse\x12*\n" +
	"\tjob_types\x18\x01 \x03(\v2\r.jack.JobTypeR\bjobTypes2\xfa\x02\n" +
	"\fAdminService\x12K\n" +
	"\x0eCreateProducer\x12\x1b.jack.CreateProducerRequest\x1a\x1c.jack.CreateProducerResponse\x12B\n" +
	"\vGetProducer\x12\x18.jack.GetProducerRequest\x1a\x19.jack.GetProducerResponse\x12H\n" +
	"\rListProducers\x12\x1a.jack.ListProducersRequest\x1a\x1b.jack.ListProducersResponse\x12H\n" +
	"\rCreateJobType\x12\x1a.jack.CreateJobTypeRequest\x1a\x1b.jack.CreateJobTypeResponse\x12E\n" +
	"\fListJobTypes\x12\x19.jack.ListJobTypesRequest\x1a\x1a.jack.ListJobTypesResponseB,Z*github.com/clerk/jack-service/proto/jackpbb\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_admin_proto_goTypes = []any{
	(*CreateProducerRequest)(nil),  // 0: jack.CreateProducerRequest
	(*CreateProducerResponse)(nil), // 1: jack.CreateProducerResponse
	(*GetProducerRequest)(nil),     // 2: jack.GetProducerRequest
	(*GetProducerResponse)(nil),    // 3: jack.GetProducerResponse
	(*ListProducersRequest)(nil),   // 4: jack.ListProducersRequest
	(*ListProducersResponse)(nil),  // 5: jack.ListProducersResponse
	(*CreateJobTypeRequest)(nil),   // 6: jack.CreateJobTypeRequest
	(*CreateJobTypeResponse)(nil),  // 7: jack.CreateJobTypeResponse
	(*ListJobTypesRequest)(nil),    // 8: jack.ListJobTypesRequest
	(*ListJobTypesResponse)(nil),   // 9: jack.ListJobTypesResponse
	(*Producer)(nil),               // 10: jack.Producer
	(Queue)(0),                     // 11: jack.Queue
	(*JobType)(nil),                // 12: jack.JobType
}
var file_admin_proto_depIdxs = []int32{
	10, // 0: jack.CreateProducerResponse.producer:type_name -> jack.Producer
	10, // 1: jack.GetProducerResponse.producer:type_name -> jack.Producer
	10, // 2: jack.ListProducersResponse.producers:type_name -> jack.Producer
	11, // 3: jack.CreateJobTypeRequest.queue:type_name -> jack.Queue
	12, // 4: jack.CreateJobTypeResponse.job_type:type_name -> jack.JobType
	12, // 5: jack.ListJobTypesResponse.job_types:type_name -> jack.JobType
	0,  // 6: jack.AdminService.CreateProducer:input_type -> jack.CreateProducerRequest
	2,  // 7: jack.AdminService.GetProducer:input_type -> jack.GetProducerRequest
	4,  // 8: jack.AdminService.ListProducers:input_type -> jack.ListProducersRequest
	6,  // 9: jack.AdminService.CreateJobType:input_type -> jack.CreateJobTypeRequest
	8,  // 10: jack.AdminService.ListJobTypes:input_type -> jack.ListJobTypesRequest
	1,  // 11: jack.AdminService.CreateProducer:output_type -> jack.CreateProducerResponse
	3,  // 12: jack.AdminService.GetProducer:output_type -> jack.GetProducerResponse
	5,  // 13: jack.AdminService.ListProducers:output_type -> jack.ListProducersResponse
	7,  // 14: jack.AdminService.CreateJobType:output_type -> jack.CreateJobTypeResponse
	9,  // 15: jack.AdminService.ListJobTypes:output_type -> jack.ListJobTypesResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	file_storage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
