// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: jack.proto

package jackpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackgroundJobs_Enqueue_FullMethodName     = "/jack.BackgroundJobs/Enqueue"
	BackgroundJobs_EnqueueBulk_FullMethodName = "/jack.BackgroundJobs/EnqueueBulk"
)

// BackgroundJobsClient is the client API for BackgroundJobs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BackgroundJobs is the main service for enqueueing background jobs.
type BackgroundJobsClient interface {
	// Enqueue a single job for background processing.
	Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
	// Enqueue multiple jobs in a single request (best-effort, non-atomic).
	EnqueueBulk(ctx context.Context, in *EnqueueBulkRequest, opts ...grpc.CallOption) (*EnqueueBulkResponse, error)
}

type backgroundJobsClient struct {
	cc grpc.ClientConnInterface
}

func NewBackgroundJobsClient(cc grpc.ClientConnInterface) BackgroundJobsClient {
	return &backgroundJobsClient{cc}
}

func (c *backgroundJobsClient) Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueResponse)
	err := c.cc.Invoke(ctx, BackgroundJobs_Enqueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backgroundJobsClient) EnqueueBulk(ctx context.Context, in *EnqueueBulkRequest, opts ...grpc.CallOption) (*EnqueueBulkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueBulkResponse)
	err := c.cc.Invoke(ctx, BackgroundJobs_EnqueueBulk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackgroundJobsServer is the server API for BackgroundJobs service.
// All implementations must embed UnimplementedBackgroundJobsServer
// for forward compatibility.
//
// BackgroundJobs is the main service for enqueueing background jobs.
type BackgroundJobsServer interface {
	// Enqueue a single job for background processing.
	Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error)
	// Enqueue multiple jobs in a single request (best-effort, non-atomic).
	EnqueueBulk(context.Context, *EnqueueBulkRequest) (*EnqueueBulkResponse, error)
	mustEmbedUnimplementedBackgroundJobsServer()
}

// UnimplementedBackgroundJobsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackgroundJobsServer struct{}

func (UnimplementedBackgroundJobsServer) Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enqueue not implemented")
}
func (UnimplementedBackgroundJobsServer) EnqueueBulk(context.Context, *EnqueueBulkRequest) (*EnqueueBulkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueBulk not implemented")
}
func (UnimplementedBackgroundJobsServer) mustEmbedUnimplementedBackgroundJobsServer() {}
func (UnimplementedBackgroundJobsServer) testEmbeddedByValue()                        {}

// UnsafeBackgroundJobsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackgroundJobsServer will
// result in compilation errors.
type UnsafeBackgroundJobsServer interface {
	mustEmbedUnimplementedBackgroundJobsServer()
}

func RegisterBackgroundJobsServer(s grpc.ServiceRegistrar, srv BackgroundJobsServer) {
	// If the following call panics, it indicates UnimplementedBackgroundJobsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackgroundJobs_ServiceDesc, srv)
}

func _BackgroundJobs_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackgroundJobsServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackgroundJobs_Enqueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackgroundJobsServer).Enqueue(ctx, req.(*EnqueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackgroundJobs_EnqueueBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackgroundJobsServer).EnqueueBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackgroundJobs_EnqueueBulk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackgroundJobsServer).EnqueueBulk(ctx, req.(*EnqueueBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackgroundJobs_ServiceDesc is the grpc.ServiceDesc for BackgroundJobs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackgroundJobs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jack.BackgroundJobs",
	HandlerType: (*BackgroundJobsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enqueue",
			Handler:    _BackgroundJobs_Enqueue_Handler,
		},
		{
			MethodName: "EnqueueBulk",
			Handler:    _BackgroundJobs_EnqueueBulk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jack.proto",
}
