// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jack.proto

package jackpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnqueueRequest represents a single job to be enqueued.
type EnqueueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Producer identifier (required).
	ProducerId string `protobuf:"bytes,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	// Job type name (required).
	JobType string `protobuf:"bytes,2,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	// Opaque payload data delivered to the consumer (optional).
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Scheduled execution time. If not set, job runs immediately.
	RunAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=run_at,json=runAt,proto3" json:"run_at,omitempty"`
	// Distributed tracing correlation ID (optional).
	TraceId string `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Caller-assigned reference echoed back in responses, used by the caller
	// to correlate results with their internal tracking (e.g., outbox row ID).
	CorrelationId string `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_jack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_jack_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueRequest) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *EnqueueRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *EnqueueRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnqueueRequest) GetRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RunAt
	}
	return nil
}

func (x *EnqueueRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *EnqueueRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// EnqueueResponse is returned after successfully enqueueing a job.
type EnqueueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique job identifier (decodable for debugging).
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Error messages about the request (e.g., unregistered producer or job type).
	ErrorMessages []string `protobuf:"bytes,2,rep,name=error_messages,json=errorMessages,proto3" json:"error_messages,omitempty"`
	// Echoed from the corresponding EnqueueRequest.correlation_id.
	CorrelationId string `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_jack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_jack_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *EnqueueResponse) GetErrorMessages() []string {
	if x != nil {
		return x.ErrorMessages
	}
	return nil
}

func (x *EnqueueResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// EnqueueBulkRequest contains multiple jobs to enqueue.
type EnqueueBulkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Jobs to enqueue.
	Jobs          []*EnqueueRequest `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueBulkRequest) Reset() {
	*x = EnqueueBulkRequest{}
	mi := &file_jack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueBulkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueBulkRequest) ProtoMessage() {}

func (x *EnqueueBulkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueBulkRequest.ProtoReflect.Descriptor instead.
func (*EnqueueBulkRequest) Descriptor() ([]byte, []int) {
	return file_jack_proto_rawDescGZIP(), []int{2}
}

func (x *EnqueueBulkRequest) GetJobs() []*EnqueueRequest {
	if x != nil {
		return x.Jobs
	}
	return nil
}

// EnqueueBulkResponse contains results for each job in the bulk request.
type EnqueueBulkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per-job results, in the same order as the request.
	Results       []*BulkResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueBulkResponse) Reset() {
	*x = EnqueueBulkResponse{}
	mi := &file_jack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueBulkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueBulkResponse) ProtoMessage() {}

func (x *EnqueueBulkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueBulkResponse.ProtoReflect.Descriptor instead.
func (*EnqueueBulkResponse) Descriptor() ([]byte, []int) {
	return file_jack_proto_rawDescGZIP(), []int{3}
}

func (x *EnqueueBulkResponse) GetResults() []*BulkResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// BulkResult represents the result of enqueueing a single job in a bulk request.
type BulkResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Position in the request array (0-indexed).
	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Job ID on success, empty on failure.
	JobId string `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Error message on failure, empty on success.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Error messages about the request (e.g., unregistered producer or job type).
	ErrorMessages []string `protobuf:"bytes,4,rep,name=error_messages,json=errorMessages,proto3" json:"error_messages,omitempty"`
	// Echoed from the corresponding EnqueueRequest.correlation_id.
	CorrelationId string `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Reason        string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkResult) Reset() {
	*x = BulkResult{}
	mi := &file_jack_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkResult) ProtoMessage() {}

func (x *BulkResult) ProtoReflect() protoreflect.Message {
	mi := &file_jack_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkResult.ProtoReflect.Descriptor instead.
func (*BulkResult) Descriptor() ([]byte, []int) {
	return file_jack_proto_rawDescGZIP(), []int{4}
}

func (x *BulkResult) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BulkResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *BulkResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BulkResult) GetErrorMessages() []string {
	if x != nil {
		return x.ErrorMessages
	}
	return nil
}

func (x *BulkResult) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BulkResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_jack_proto protoreflect.FileDescriptor

const file_jack_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"jack.proto\x12\x04jack\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x01\n" +
	"\x0eEnqueueRequest\x12\x1f\n" +
	"\vproducer_id\x18\x01 \x01(\tR\n" +
	"producerId\x12\x19\n" +
	"\bjob_type\x18\x02 \x01(\tR\ajobType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x121\n" +
	"\x06run_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05runAt\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\"v\n" +
	"\x0fEnqueueResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12%\n" +
	"\x0eerror_messages\x18\x02 \x03(\tR\rerrorMessages\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\">\n" +
	"\x12EnqueueBulkRequest\x12(\n" +
	"\x04jobs\x18\x01 \x03(\v2\x14.jack.EnqueueRequestR\x04jobs\"A\n" +
	"\x13EnqueueBulkResponse\x12*\n" +
	"\aresults\x18\x01 \x03(\v2\x10.jack.BulkResultR\aresults\"\xb5\x01\n" +
	"\n" +
	"BulkResult\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12%\n" +
	"\x0eerror_messages\x18\x04 \x03(\tR\rerrorMessages\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason2\x8c\x01\n" +
	"\x0eBackgroundJobs\x126\n" +
	"\aEnqueue\x12\x14.jack.EnqueueRequest\x1a\x15.jack.EnqueueResponse\x12B\n" +
	"\vEnqueueBulk\x12\x18.jack.EnqueueBulkRequest\x1a\x19.jack.EnqueueBulkResponseB,Z*github.com/clerk/jack-service/proto/jackpbb\x06proto3"

var (
	file_jack_proto_rawDescOnce sync.Once
	file_jack_proto_rawDescData []byte
)

func file_jack_proto_rawDescGZIP() []byte {
	file_jack_proto_rawDescOnce.Do(func() {
		file_jack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jack_proto_rawDesc), len(file_jack_proto_rawDesc)))
	})
	return file_jack_proto_rawDescData
}

var file_jack_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_jack_proto_goTypes = []any{
	(*EnqueueRequest)(nil),        // 0: jack.EnqueueRequest
	(*EnqueueResponse)(nil),       // 1: jack.EnqueueResponse
	(*EnqueueBulkRequest)(nil),    // 2: jack.EnqueueBulkRequest
	(*EnqueueBulkResponse)(nil),   // 3: jack.EnqueueBulkResponse
	(*BulkResult)(nil),            // 4: jack.BulkResult
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_jack_proto_depIdxs = []int32{
	5, // 0: jack.EnqueueRequest.run_at:type_name -> google.protobuf.Timestamp
	0, // 1: jack.EnqueueBulkRequest.jobs:type_name -> jack.EnqueueRequest
	4, // 2: jack.EnqueueBulkResponse.results:type_name -> jack.BulkResult
	0, // 3: jack.BackgroundJobs.Enqueue:input_type -> jack.EnqueueRequest
	2, // 4: jack.BackgroundJobs.EnqueueBulk:input_type -> jack.EnqueueBulkRequest
	1, // 5: jack.BackgroundJobs.Enqueue:output_type -> jack.EnqueueResponse
	3, // 6: jack.BackgroundJobs.EnqueueBulk:output_type -> jack.EnqueueBulkResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_jack_proto_init() }
func file_jack_proto_init() {
	if File_jack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jack_proto_rawDesc), len(file_jack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jack_proto_goTypes,
		DependencyIndexes: file_jack_proto_depIdxs,
		MessageInfos:      file_jack_proto_msgTypes,
	}.Build()
	File_jack_proto = out.File
	file_jack_proto_goTypes = nil
	file_jack_proto_depIdxs = nil
}
