// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: storage.proto

package jackpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Queue priority levels for job execution.
type Queue int32

const (
	Queue_QUEUE_UNSPECIFIED Queue = 0
	Queue_QUEUE_IMMEDIATE   Queue = 1 // SLA: ≤5 seconds
	Queue_QUEUE_HIGH        Queue = 2 // SLA: ≤15 seconds
	Queue_QUEUE_MEDIUM      Queue = 3 // SLA: ≤1 minute
	Queue_QUEUE_LOW         Queue = 4 // SLA: ≤5 minutes
)

// Enum value maps for Queue.
var (
	Queue_name = map[int32]string{
		0: "QUEUE_UNSPECIFIED",
		1: "QUEUE_IMMEDIATE",
		2: "QUEUE_HIGH",
		3: "QUEUE_MEDIUM",
		4: "QUEUE_LOW",
	}
	Queue_value = map[string]int32{
		"QUEUE_UNSPECIFIED": 0,
		"QUEUE_IMMEDIATE":   1,
		"QUEUE_HIGH":        2,
		"QUEUE_MEDIUM":      3,
		"QUEUE_LOW":         4,
	}
)

func (x Queue) Enum() *Queue {
	p := new(Queue)
	*p = x
	return p
}

func (x Queue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Queue) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_proto_enumTypes[0].Descriptor()
}

func (Queue) Type() protoreflect.EnumType {
	return &file_storage_proto_enumTypes[0]
}

func (x Queue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Queue.Descriptor instead.
func (Queue) EnumDescriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

// Producer is a registered producer that can enqueue jobs.
type Producer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProducerId    string                 `protobuf:"bytes,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RateLimitRps  int32                  `protobuf:"varint,4,opt,name=rate_limit_rps,json=rateLimitRps,proto3" json:"rate_limit_rps,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Producer) Reset() {
	*x = Producer{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Producer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Producer) ProtoMessage() {}

func (x *Producer) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Producer.ProtoReflect.Descriptor instead.
func (*Producer) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Producer) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *Producer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Producer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Producer) GetRateLimitRps() int32 {
	if x != nil {
		return x.RateLimitRps
	}
	return 0
}

func (x *Producer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Producer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// JobType defines a type of job that a producer can enqueue.
type JobType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProducerId    string                 `protobuf:"bytes,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Queue         Queue                  `protobuf:"varint,3,opt,name=queue,proto3,enum=jack.Queue" json:"queue,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobType) Reset() {
	*x = JobType{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobType) ProtoMessage() {}

func (x *JobType) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobType.ProtoReflect.Descriptor instead.
func (*JobType) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *JobType) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *JobType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobType) GetQueue() Queue {
	if x != nil {
		return x.Queue
	}
	return Queue_QUEUE_UNSPECIFIED
}

func (x *JobType) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *JobType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JobType) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JobType) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ProducersFile is the top-level structure for producers.json
type ProducersFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Producers     []*Producer            `protobuf:"bytes,1,rep,name=producers,proto3" json:"producers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProducersFile) Reset() {
	*x = ProducersFile{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProducersFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducersFile) ProtoMessage() {}

func (x *ProducersFile) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducersFile.ProtoReflect.Descriptor instead.
func (*ProducersFile) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *ProducersFile) GetProducers() []*Producer {
	if x != nil {
		return x.Producers
	}
	return nil
}

// JobTypesFile is the top-level structure for job_types.json
type JobTypesFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobTypes      []*JobType             `protobuf:"bytes,1,rep,name=job_types,json=jobTypes,proto3" json:"job_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobTypesFile) Reset() {
	*x = JobTypesFile{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobTypesFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobTypesFile) ProtoMessage() {}

func (x *JobTypesFile) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobTypesFile.ProtoReflect.Descriptor instead.
func (*JobTypesFile) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *JobTypesFile) GetJobTypes() []*JobType {
	if x != nil {
		return x.JobTypes
	}
	return nil
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\x04jack\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\x01\n" +
	"\bProducer\x12\x1f\n" +
	"\vproducer_id\x18\x01 \x01(\tR\n" +
	"producerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12$\n" +
	"\x0erate_limit_rps\x18\x04 \x01(\x05R\frateLimitRps\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9a\x02\n" +
	"\aJobType\x12\x1f\n" +
	"\vproducer_id\x18\x01 \x01(\tR\n" +
	"producerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\x05queue\x18\x03 \x01(\x0e2\v.jack.QueueR\x05queue\x12\x1f\n" +
	"\vmax_retries\x18\x04 \x01(\x05R\n" +
	"maxRetries\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"=\n" +
	"\rProducersFile\x12,\n" +
	"\tproducers\x18\x01 \x03(\v2\x0e.jack.ProducerR\tproducers\":\n" +
	"\fJobTypesFile\x12*\n" +
	"\tjob_types\x18\x01 \x03(\v2\r.jack.JobTypeR\bjobTypes*d\n" +
	"\x05Queue\x12\x15\n" +
	"\x11QUEUE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fQUEUE_IMMEDIATE\x10\x01\x12\x0e\n" +
	"\n" +
	"QUEUE_HIGH\x10\x02\x12\x10\n" +
	"\fQUEUE_MEDIUM\x10\x03\x12\r\n" +
	"\tQUEUE_LOW\x10\x04B,Z*github.com/clerk/jack-service/proto/jackpbb\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_storage_proto_goTypes = []any{
	(Queue)(0),                    // 0: jack.Queue
	(*Producer)(nil),              // 1: jack.Producer
	(*JobType)(nil),               // 2: jack.JobType
	(*ProducersFile)(nil),         // 3: jack.ProducersFile
	(*JobTypesFile)(nil),          // 4: jack.JobTypesFile
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_storage_proto_depIdxs = []int32{
	5, // 0: jack.Producer.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: jack.Producer.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: jack.JobType.queue:type_name -> jack.Queue
	5, // 3: jack.JobType.created_at:type_name -> google.protobuf.Timestamp
	5, // 4: jack.JobType.updated_at:type_name -> google.protobuf.Timestamp
	1, // 5: jack.ProducersFile.producers:type_name -> jack.Producer
	2, // 6: jack.JobTypesFile.job_types:type_name -> jack.JobType
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		EnumInfos:         file_storage_proto_enumTypes,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
